document.writeln("<style type=\'text/css\'>");
document.writeln(".zj_js{width:100%;   margin: auto; overflow: hidden;}");
document.writeln(".zj_l{width:50%; float: left;  overflow: hidden;}");
document.writeln(".zj_l h1{ font-size: 0.175rem; color: #694245;}");
document.writeln(".zj_l h1 b{font-size: 0.125rem; font-weight: normal; margin-left: 2%;}");
document.writeln(".zj_l h3{ width:1.445rem; height: 0.15rem; font-size: 0.08rem; text-align: center; line-height: 0.15rem; margin-top: 0.02rem; color: #fff; font-weight: bold; padding: 2%; background: #694245;}");
document.writeln(".zj_l ul{margin-top: 6%; padding-bottom: 6%;}");
document.writeln(".zj_l ul li{background: url(images/ban_xq.jpg) no-repeat left center; font-size: 0.07rem; line-height: 0.15rem; color: #444; text-indent: 1em;}");
document.writeln(".zj_l p{font-size: 0.07rem; color: #666; line-height: 0.12rem;}");
document.writeln(".zj_r{width:50%; float: right; background: url(images/zjlb_bg.png) no-repeat top right; background-size: 4.9%; position: relative;}");
document.writeln(".zj_r img{width: 90%;}");
document.writeln("");
document.writeln(".zj_lz{width:50%; float: right;  overflow: hidden;}");
document.writeln(".zj_lz h1{ font-size: 0.175rem; color: #694245;}");
document.writeln(".zj_lz h1 b{font-size: 0.125rem; font-weight: normal; margin-left: 2%;}");
document.writeln(".zj_lz h3{ width:1.445rem; height: 0.15rem; font-size: 0.08rem; text-align: center; line-height: 0.15rem; margin-top: 0.02rem; color: #fff; font-weight: bold; padding: 2%; background: #694245;}");
document.writeln(".zj_lz ul{margin-top: 6%; padding-bottom: 6%;}");
document.writeln(".zj_lz ul li{background: url(images/ban_xq.jpg) no-repeat left center; font-size: 0.07rem; line-height: 0.15rem; color: #444; text-indent: 1em;}");
document.writeln(".zj_lz p{font-size: 0.07rem; color: #666; line-height: 0.12rem;}");
document.writeln(".zj_rz{width:50%; float: left; background: url(images/zjlb_bg2.png) no-repeat top left; background-size: 5%; position: relative;}");
document.writeln(".zj_rz img{width: 90%; margin-left: 7%;}");
document.writeln("</style>");

document.writeln("<div class=\'zj_js\'>");
document.writeln("          <div class=\'zj_l\'>");
document.writeln("              <h1>王明利<b>博士/主任医师</b></h1>");
document.writeln("              <h3>27年专注脂肪精雕  20000多例成功案例</h3>");
document.writeln("              <ul>");
document.writeln("                  <li>毕业于中国人民解放军第四军医大学</li>");
document.writeln("                  <li> 亚洲活性脂肪编码移植技术研创人</li>");
document.writeln("                  <li>中国整形外科导师级名医学者</li>");
document.writeln("                  <li>润美玉之光脂肪精雕中心技术院长</li>");
document.writeln("                  <li>中国整形外科导师级主任医师博士</li>");
document.writeln("                  <li>自体活性脂肪移植技术研创人</li>");
document.writeln("                  <li>中国整形美容协会会员</li>");
document.writeln("                  <li>中国医师协会美容与整形分会会员</li>");
document.writeln("                  <li>德国Body-jet水动力吸脂丰胸术指定专家</li>");
document.writeln("              </ul>");
document.writeln("          </div>");
document.writeln("          <div class=\'zj_r\'>");
document.writeln("              <img src=\'images/zj.jpg\'>");
document.writeln("          </div>");
document.writeln("      </div>  ");
document.writeln("      <div class=\'zj_js\'>");
document.writeln("          <div class=\'zj_lz\'>");
document.writeln("              <h1>张亮<b>院长/执业医师</b></h1>");
document.writeln("              <h3>润美玉之光微整注射中心技术院长</h3>");
document.writeln("              <ul>");
document.writeln("                  <li>亚洲微整形美容协会 会员</li>");
document.writeln("                  <li> 中国医师协会 整形与美容分会 会员</li>");
document.writeln("                  <li>中韩整形产业促进会  受邀出访学者</li>");
document.writeln("                  <li>韩国整形美容产业协会 会员</li>");
document.writeln("                  <li>Botox（Allergan U.S.A） 认证注射专家</li>");
document.writeln("                  <li>爱贝芙（Hafod Bioscience B.V.）  </li>");
document.writeln("                  <p style=\'color: #444; text-indent: 1em;\'>认证注射专家</p>");
document.writeln("                  <li>瑞蓝(Q-Med Sweden)  认证注射专家</li>");
document.writeln("                  <li>润百颜（华熙生物） 指定注射专家</li>");
document.writeln("                  <li>水动力活性编码脂肪移植专家</li>");
document.writeln("              </ul>");
document.writeln("          </div>");
document.writeln("          <div class=\'zj_rz\'>");
document.writeln("              <img src=\'images/zj_zl.jpg\'>");
document.writeln("          </div>");
document.writeln("      </div>");